data:
  path: data/processed/options_with_returns_scaled.csv
  date_col: date
  target: ret_dh_w_adj
  target_scale:
    kind: gamma
    abs: true
    floor: 1e-6
  features:
  - corp
  - moneyness
  - tau
  - dte
  - dte_1
  - dte_2
  - dte_3p
  - delta_model
  - vega_model
  - theta_model
  - gamma_scaled
  - atm_iv
  - atm_iv_chg
  - atm_term_slope
  - smile_slope
  - rv_ann_past
  - ivrv_pred
  - ivrv_ratio_pred
  - convexity_proxy
  - vega_ivchg_proxy
  - opt_spread_hi
  - baspread_chg
  - baspread_z
  - rv_chg
  - rv_z
  - pfb
  - pfb_z
  - indmom_z
  - realskew_chg
  - realskew_z
  - public_chg
  - public_z
  - rtrs_pos_chg
  - rtrs_pos_z
  - rtrs_neg_chg
  - rtrs_neg_z
  - rtrs_neu_chg
  - rtrs_neu_z
  - rtrs_total_chg
  - rtrs_total_z
  - reddit_pos_chg
  - reddit_pos_z
  - reddit_neg_chg
  - reddit_neg_z
  - reddit_neu_chg
  - reddit_neu_z
  - reddit_total_chg
  - reddit_total_z
  dropna: false
  atm_band: 0.03
  side: null
  cp_col: cp
  call_values:
  - 1
  - C
  put_values:
  - 0
  - -1
  - P
  callput: all
  moneyness: atm
diagnostics:
  generic: true
  linear: false
  topk_scatter: 8
split:
  train_frac: 0.7
  val_frac: 0.15
  period: D
forecast:
  horizon_periods: 1
train:
  models:
  - ols
  - ridge_cv
  - enet_pairs
  - huber
  - lgbm_gbdt
  - lgbm_dart
  - torch_ffn
  - pcr
  - pls
  - rf
  - zero
  refit_on: train_val
  random_state: 42
  y_winsor_p: 0.0
  y_transform: yeo-johnson
  y_asinh_scale: 0.5
  min_feature_coverage: 0.9
tuning:
  method: random
  n_iter: 5
  cv:
    n_splits: 1
    min_train_periods: 6
    val_periods: 1
    period: W-FRI
    gap: 0W
  select:
    rule: one_se
    tie_breaker: r2_oos
  spaces:
    torch_ffn:
      hidden_dims:
        values:
        - - 32
        - - 64
        - - 128
        - - 32
          - 32
        - - 64
          - 64
        - - 128
          - 128
        - - 32
          - 32
          - 32
        - - 64
          - 64
          - 64
        - - 128
          - 128
          - 128
      activation:
        values:
        - relu
        - tanh
        - gelu
      dropout:
        dist: uniform
        low: 0.0
        high: 0.25
      lr:
        dist: loguniform
        low: 0.0005
        high: 0.05
      weight_decay:
        dist: loguniform
        low: 1.0e-06
        high: 0.001
      epochs:
        dist: int_uniform
        low: 30
        high: 100
      patience:
        values:
        - 8
        - 12
        - 16
      batch_size:
        values:
        - 512
        - 1024
        - 2048
      seed:
        values:
        - 42
    lgbm_gbdt:
      n_estimators:
        dist: int_loguniform
        low: 200
        high: 4000
      learning_rate:
        dist: loguniform
        low: 0.02
        high: 0.1
      max_depth:
        dist: int_uniform
        low: 4
        high: 10
      num_leaves:
        dist: int_uniform
        low: 15
        high: 127
      min_child_samples:
        dist: int_uniform
        low: 50
        high: 300
      feature_fraction:
        values:
        - 0.7
        - 0.8
        - 0.9
        - 1.0
      bagging_fraction:
        values:
        - 0.7
        - 0.8
        - 0.9
      bagging_freq:
        values:
        - 1
        - 3
        - 5
      reg_alpha:
        values:
        - 0.0
        - 0.1
        - 0.5
        - 1.0
      reg_lambda:
        values:
        - 0.0
        - 1.0
        - 10.0
        - 50.0
      min_split_gain:
        values:
        - 0.0
        - 0.01
      verbose:
        values:
        - -1
      random_state:
        values:
        - 42
    lgbm_dart:
      n_estimators:
        dist: int_loguniform
        low: 400
        high: 6000
      learning_rate:
        dist: loguniform
        low: 0.02
        high: 0.1
      max_depth:
        dist: int_uniform
        low: 4
        high: 10
      num_leaves:
        dist: int_uniform
        low: 15
        high: 127
      min_child_samples:
        dist: int_uniform
        low: 50
        high: 300
      feature_fraction:
        values:
        - 0.7
        - 0.8
        - 0.9
        - 1.0
      bagging_fraction:
        values:
        - 0.7
        - 0.8
        - 0.9
      bagging_freq:
        values:
        - 1
        - 3
        - 5
      reg_alpha:
        values:
        - 0.0
        - 0.1
        - 0.5
        - 1.0
      reg_lambda:
        values:
        - 0.0
        - 1.0
        - 10.0
        - 50.0
      min_split_gain:
        values:
        - 0.0
        - 0.01
      drop_rate:
        values:
        - 0.05
        - 0.1
        - 0.15
      skip_drop:
        values:
        - 0.25
        - 0.5
      verbose:
        values:
        - -1
      random_state:
        values:
        - 42
    random_forest:
      n_estimators:
        values:
        - 300
        - 600
        - 1000
      max_depth:
        values:
        - null
        - 6
        - 10
        - 15
      min_samples_leaf:
        values:
        - 1
        - 2
        - 5
        - 10
      max_features:
        values:
        - sqrt
        - log2
        - 0.5
      bootstrap:
        values:
        - true
    enet_pairs:
      top_k:
        dist: int_uniform
        low: 16
        high: 128
      min_abs_corr:
        dist: uniform
        low: 0.05
        high: 0.1
      l1_ratio:
        values:
        - 0.2
        - 0.4
        - 0.6
        - 0.8
      n_alphas:
        values:
        - 60
      eps:
        values:
        - 0.001
      max_iter:
        values:
        - 200000
      tol:
        values:
        - 0.0001
        - 0.0003
      selection:
        values:
        - random
      fit_intercept:
        values:
        - true
      random_state:
        values:
        - 42
    ridge:
      alpha:
        dist: loguniform
        low: 1.0e-06
        high: 0.01
      fit_intercept:
        values:
        - true
    pcr:
      n_components:
        values:
        - 1
        - 2
        - 3
        - 4
        - 5
        - 6
      standardize:
        values:
        - true
      whiten:
        values:
        - false
      svd_solver:
        values:
        - auto
      reg:
        values:
        - ols
    pls:
      n_components:
        values:
        - 1
        - 2
        - 3
        - 4
        - 5
        - 6
      standardize:
        values:
        - true
      max_iter:
        values:
        - 500
        - 1000
      tol:
        values:
        - 1.0e-06
        - 1.0e-05
      imputer_strategy:
        values:
        - mean
model_params:
  ols:
    add_const: true
    nw_lags: 0
  ridge_cv:
    alphas:
    - 0.001
    - 0.01
    - 0.1
    - 0.3
    - 1
    - 3
    - 10
    - 30
    - 100
    - 300
    - 1000
    cv: 5
    scoring: neg_mean_absolute_error
    imputer_strategy: mean
  enet_pairs:
    add_original: true
    max_pairs: 3000
    top_k: 150
    min_abs_corr: 0.02
    verbose: false
    cv: 5
    group_map:
      moneyness: I
      tau: I
      iv: V
      atm_iv: V
      rv_ann_past: R
      ivrv_pred: R
      ivrv_ratio_pred: R
      delta_model: G
      vega_model: G
      theta_model: G
      gamma_scaled: G
      F: S
      baspread: S
      rv: S
      pfb: S
      indmom: S
      realskew: S
    allowed_pairs:
    - - I
      - S
    - - V
      - S
    - - R
      - S
    - - I
      - G
    - - V
      - G
    - - R
      - G
  lgbm_gbdt:
    n_jobs: -1
    objective: mse
    metric: mse
    random_state: 42
  lgbm_dart:
    n_jobs: -1
    objective: mse
    metric: mse
    boosting_type: dart
    random_state: 42
  torch_ffn:
    hidden_dims:
    - 256
    - 256
    - 128
    dropout: 0.1
    activation: relu
    epochs: 80
    batch_size: 2048
    lr: 0.001
    weight_decay: 0.0001
    patience: 12
    device: auto
    verbose: true
    amp: true
benchmark: zero
outputs:
  dir: C:\Users\kawah\Documents\predicting-returns\results\experiments\tuned-debiased-gamma-small\all-atm-20250928-195903-0002
  predictions_csv: predictions_test.csv
  metrics_csv: metrics_test.csv
  cv_dir: cv
  coeffs_ols_csv: coefficients_ols.csv
  coeffs_ridge_csv: coefficients_ridge.csv
  coeffs_enet_pairs_csv: coefficients_enet_pairs.csv
  coeffs_enet_pairs_orig_csv: coefficients_enet_pairs_orig.csv
  enet_cv_curve_csv: enet_cv_curve.csv
  enet_summary_json: enet_summary.json
  index_label: row_id
run_tag: all-atm-20250928-195903-0002
